---
version: '3.3'

services:
  db:
    image: docker-reg.sirmaplatform.com/sep-postgres:2.24.0
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.com.sirma.sep.db==yes
    environment:
      - WORK_MEM=48MB
      - MAX_CONNECTIONS=500
      - MAX_PREPARED_TRANSACTIONS=500
      - EFFECTIVE_CACHE_SIZE=3072MB
      - SHARED_BUFFERS=1280MB
    ports:
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr-audit:
    image: docker-reg.sirmaplatform.com/sep-solr-audit:2.12.0-u1
    deploy:
      placement:
          constraints:
              - node.labels.com.sirma.sep.solr.audit==yes
    environment:
      - PROXY_SERVICE_DEF_MAIN=internal:solr-audit:/solr/audit/:http://solr-audit:8983
    volumes:
      - solr_audit_data:/var/lib/solr
      - solr_audit_logs:/opt/solr/server/logs

  solr:
    image: docker-reg.sirmaplatform.com/sep-solr-core:2.12.0-u1
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.solr.core==yes
    environment:
      - SOLR_HEAP=4096m
      - PROXY_SERVICE_DEF_MAIN=internal:solr-core:/solr/core/:http://solr:8983
    volumes:
      - solr_core_data:/var/lib/solr
      - solr_core_logs:/opt/solr/server/logs

  export:
    image: docker-reg.sirmaplatform.com/export:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.other==yes
    volumes:
      - export_data:/opt/export/output
      - export_logs:/opt/export/logs

  compare:
    image: docker-reg.sirmaplatform.com/compare-pdf:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.other==yes
    volumes:
      - compare-pdf_data:/opt/compare-pdf/output
      - compare-pdf_logs:/opt/compare-pdf/logs

  idp:
    image: docker-reg.sirmaplatform.com/cs-wso2is:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.idp==yes
    environment:
      - HOST_NAME=idp
      - LDAP_USE_EMBEDDED=false
      - LDAP_HOST=ldap
      - LDAP_PORT=10389
      - LDAP_USERNAME=cn=Manager,dc=SIRMAITT,dc=BG
      - LDAP_PASSWORD=secret
      - PROXY_SERVICE_DEF_MAIN=secure:idp:/sso:https://idp:9443
    volumes:
      - idp_data:/opt/wso2is/repository/data
      - idp_logs:/opt/wso2is/repository/logs
      - /etc/sep/certs:/opt/wso2is/repository/resources/keystore

  keycloak:
    image: docker-reg.sirmaplatform.com/cs-keycloak:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.idp==yes
    env_file: keycloak.env
    environment:
      PROXY_SERVICE_DEF_MAIN: secure:keycloak:/auth:http://keycloak:8080
      MASTER_DISPLAY_NAME: "Conservation Space"
      MASTER_DISPLAY_NAME_HTML: "Conservation Space"
    ports:
      - 8090:8080
    volumes:
      - keycloak_data:/opt/keycloak/standalone/data
      - keycloak_logs:/opt/keycloak/standalone/log

  ldap:
    image: docker-reg.sirmaplatform.com/sep-openldap:2.25.0
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.idp==yes
    volumes:
      - ldap_data:/var/lib/openldap
      - ldap_logs:/var/log/openldap

  alfresco:
    image: docker-reg.sirmaplatform.com/sep-alfresco:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.dms==yes
    environment:
      - PROXY_SERVICE_DEF_MAIN=internal:alfresco:/alfresco:http://alfresco:8080
      - LDAP_HOST=ldap
      - LDAP_PORT=10389
      - LDAP_USERNAME=cn\=Manager,dc\=SIRMAITT,dc\=BG
      - LDAP_PASSWORD=secret
      - JAVA_OPTS=-XX:MaxPermSize=512m -Xms4g -Xmx4g -XX:+UseG1GC
    volumes:
      - alfresco_logs:/opt/tomcat/logs
      - alfresco_data:/var/lib/alfresco
      - alfresco_solr_data:/var/lib/alfresco-solr

  graphdb:
    image: docker-reg.sirmaplatform.com/graphdb:8.3.1-u5
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.semantic==yes
    environment:
      - GDB_HEAP_SIZE=7g
      - PROXY_SERVICE_DEF_MAIN=internal:graphdb:/graphdb/:http://graphdb:8080
    ports:
      - 8091:8091
    volumes:
      - gdb_data:/var/lib/graphdb
      - gdb_logs:/opt/graphdb/logs
      - /etc/sep/licenses/graphdb.license:/opt/graphdb/conf/graphdb.license

  ocr:
    image: docker-reg.sirmaplatform.com/ocr-service:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.ocr==yes

  content-preview:
    image: docker-reg.sirmaplatform.com/content-preview:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.preview==yes
    volumes:
      - content_preview_logs:/var/log/preview
    environment:
      - PREVIEW_LOG_LEVEL=info
    volumes:
      - content-preview_logs:/var/log/preview

  image-processing:
    image: docker-reg.sirmaplatform.com/image-processing:1.0.2
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.iiif==yes
    volumes:
      - vsftpd_data:/data
      - iiif_out:/var/www/localhost/images

  iiif:
    image: docker-reg.sirmaplatform.com/iip-server:6.0.0
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.iiif==yes
    env_file: iiif.env
    environment:
      - PROXY_SERVICE_DEF_MAIN=secure:iiif:/iiif:http://iiif
    volumes:
      - vsftpd_data:/data
      - iiif_out:/var/www/localhost/images
  ftp:
    image: docker-reg.sirmaplatform.com/vsftpd:3.0.3
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.iiif==yes
    environment:
      - PASV_PROMISCUOUS=YES
    volumes:
      - vsftpd_data:/var/lib/vsftpd

  iiif-access:
    image: docker-reg.sirmaplatform.com/apache-server:1.1
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.iiif==yes
    volumes:
      - vsftpd_data:/var/www/html

  wildfly:
    image: docker-reg.sirmaplatform.com/cs-wildfly:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.web==yes
    ports:
      - 8787:8787
      - 9990:9990
    volumes:
      - sep_data:/var/lib/sep
      - wildfly_logs:/opt/wildfly/standalone/log
      - /etc/sep/keystores:/opt/wildfly/standalone/configuration/sep/certs
      - /etc/sep/assets:/etc/sep/assets
      - wildfly_content:/opt/wildfly/standalone/data
    env_file: wildfly.env
    environment:
      - DB_NAME_AUDIT=sep
      - IDP_HOST=idp
      - IDP_PORT=9443
      - REMOTE_DEBUG=yes
      - PROXY_SERVICE_DEF_MAIN=secure:sep:/remote:http://wildfly:8080
      - PROXY_SERVICE_DEF_PROMETHEUS=internal:sep-prometheus:/emf/prometheus:http://wildfly:8080
      - JAVA_OPTS=-XX:MaxPermSize=512m -Xms4g -Xmx4g -XX:+UseG1GC -Djava.net.preferIPv4Stack=true


  ui:
    image: docker-reg.sirmaplatform.com/sep-ui:2.28.0-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.web==yes
    environment:
      - BACKEND_PROTOCOL=http
      - BACKEND_ADDR=wildfly:8080
      - BACKEND_CONTEXT_PATH=emf
      - PROXY_SERVICE_DEF_MAIN=secure:ui:/:http://ui
  proxy:
    image: docker-reg.sirmaplatform.com/http-proxy:2.28.0-SNAPSHOT
    env_file: proxy.env
    deploy:
      placement:
        constraints:
          - node.labels.com.sirma.sep.web==yes
    volumes:
      - proxy_logs:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/sep/certs:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080

volumes:
    pg_data:
    gdb_data:
    gdb_logs:
    gdb_worker2_data:
    gdb_worker2_logs:
    gdb_worker3_data:
    gdb_worker3_logs:
    vsftpd_data:
    iiif_out:
    solr_core_data:
    solr_core_logs:
    solr_audit_data:
    solr_audit_logs:
    idp_data:
    idp_logs:
    ldap_data:
    ldap_logs:
    alfresco_data:
    alfresco_solr_data:
    alfresco_logs:
    vsftpd_data:
    iiif_out:
    keycloak_data:
    keycloak_logs:
    wildfly_logs:
    wildfly_content:
    sep_data:
    content_preview_logs:
    proxy_logs:
    export_data:
    export_logs:
    compare-pdf_data:
    compare-pdf_logs:
    content-preview_logs:
