- name: Set to install Zimbra Collaboration 8.7.9 - Open Source Edition
  set_fact: zmurl=https://files.zimbra.com/downloads/8.7.9_GA/

- name: Check if your distro is Ubuntu Server 16.04 LTS
  set_fact: zmpkg=zcs-8.7.9_GA_1794.UBUNTU16_64.20170505054622
  when: ansible_distribution_major_version|int >= 16

- name: Check if your distro is Ubuntu Server 14.04 LTS
  set_fact: zmpkg=zcs-8.7.9_GA_1794.UBUNTU14_64.20170505054622
  when: ansible_distribution_major_version|int >= 14 and ansible_distribution_major_version|int <= 15
