- name: Set to install Zimbra Collaboration 8.7.9 - Open Source Edition
  set_fact: zmurl=https://files.zimbra.com/downloads/8.7.9_GA/

- name: Check if your distro is Red Hat Enterprise Linux or CentOS (Major 6)
  set_fact: zmpkg=zcs-8.7.9_GA_1794.RHEL6_64.20170505054622
  when: ansible_distribution_major_version == "6"

- name: Check if your distro is Red Hat Enterprise Linux or CentOS (Major 7)
  set_fact: zmpkg=zcs-8.7.9_GA_1794.RHEL7_64.20170505054622
  when: ansible_distribution_major_version == "7"
