[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"
