env:
  browser: true
  es6: true
parser: 'babel-eslint'
parserOptions:
  sourceType: module
globals:
  angular: true
  PluginRegistry: true
  $: true
  CKEDITOR: true
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - vars: all
      args: none
  curly:
    - error
    - all
  comma-dangle:
    - error
    - never
  object-shorthand:
    - error
    - always
