# Main entrypoint for zimbra-integration role

- include: jetty.yml
- include: certificates.yml
- include: skins.yml
- include: zimlets.yml
- include: auth.yml
- include: logo.yml
- include: whitelist.yml

- name: Restart Zimbra
  shell: sudo systemctl restart zimbra