# Content preview should expose a port for health checking, but cannot rely on it because there is no JMS broker to
# connect to in order to become healthy
addr:
  tcp://0.0.0.0:8300:
    reachable: true
