# Default mime types support mapping. Mapping added at the end of the list will take precedence over previous entries.
# To use them, the application must be provided with --spring.config.name argument which should include the mimetypes file name.

content.preview.mime-types:

  # Generic mime types
  - name: application/pdf
    preview: self
    thumbnail: no

  - name: application/json
    preview: yes
    thumbnail: no

  - name: text/.*
    preview: yes
    thumbnail: no

  - name: image/.*
    preview: self
    thumbnail: yes

  - name: video/.*
    preview: no
    thumbnail: yes

  - name: video/webm
    preview: no
    thumbnail: no

  # MS Office
  - name: application/vnd.ms-.*
    preview: yes
    thumbnail: no

  - name: application/(msword|excel|x-excel)$
    preview: yes
    thumbnail: no

  - name: application/.*officedocument.*
    preview: yes
    thumbnail: no

  # Libre Office
  - name: application/.*opendocument.*
    preview: yes
    thumbnail: no
